---
abstract: 'OAuth credential for Catalyst::Plugin::Authentication framework.'
author:
  - 'Cosmin Budrica <cosmin@sinapticode.com>'
build_requires:
  Catalyst::Runtime: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-Credential-OAuth
no_index:
  directory:
    - inc
    - t
requires:
  LWP::UserAgent: 0
  Moose: 0
  Net::OAuth: 0
  String::Random: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
